import { useEffect, useRef, useState } from "react";
import type { AgentStage } from "./types";
interface Props{tab:"preview"|"files"|"agent";projectName:string;projectId:string;previewOnline:boolean;previewKey:number;stage:AgentStage;jobId:string|null;activitySteps:Array<{iteration:number;tool:string;success:boolean}>;activityEvents:Array<{id:number;timestamp:number;iteration:number;type:string;tool?:string;message:string}>;currentActivity:string;problems:Array<{message:string;source?:string}>;productPlan:{goal:string;productType:string;pages:string[];components:string[];acceptanceCriteria:string[]}|null;onTabChange:(x:"preview"|"files"|"agent")=>void;onRefresh:()=>void;onRepair:()=>void;onOpenChat:()=>void}
const stages=[["analyzing","Analyze"],["planning","Plan"],["editing","Build"],["testing","Verify"],["completed","Done"]] as const;
export function BuilderTools(p:Props){
 const [device,setDevice]=useState<"desktop"|"tablet"|"mobile">("desktop"),[files,setFiles]=useState<string[]>([]),[selected,setSelected]=useState(""),[content,setContent]=useState(""),[saved,setSaved]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""); const frame=useRef<HTMLIFrameElement>(null); const dirty=content!==saved;
 useEffect(()=>{if(p.tab!=="files")return;setLoading(true);setError("");fetch("/api/projects/"+encodeURIComponent(p.projectId)+"/files").then(r=>r.json()).then(d=>setFiles(d.files??[])).catch(e=>setError(String(e))).finally(()=>setLoading(false))},[p.tab,p.projectId,p.previewKey]);
 useEffect(()=>{if(!selected)return;setLoading(true);fetch("/api/projects/"+encodeURIComponent(p.projectId)+"/file?path="+encodeURIComponent(selected)).then(r=>r.json()).then(d=>{setContent(d.content??"");setSaved(d.content??"")}).catch(e=>setError(String(e))).finally(()=>setLoading(false))},[selected,p.projectId]);
 const save=async()=>{if(!selected||!dirty)return;setLoading(true);try{const r=await fetch("/api/projects/"+encodeURIComponent(p.projectId)+"/file",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:selected,content})});if(!r.ok)throw new Error("Save failed");setSaved(content);p.onRefresh()}catch(e){setError(String(e))}finally{setLoading(false)}};
 if(p.tab==="preview")return <section className="nx-tool"><div className="nx-tool-head"><div><span>PREVIEW</span><strong>{p.previewOnline?"Live application":"Waiting for first build"}</strong></div><div className="nx-tool-actions"><button type="button" onClick={p.onRefresh}>↻ Refresh</button><button type="button" onClick={()=>window.open("/api/preview/"+p.projectId+"/index.html","_blank","noopener,noreferrer")}>Open ↗</button></div></div>{p.previewOnline?<><div className="nx-device-tabs">{(["desktop","tablet","mobile"] as const).map(x=><button key={x} className={device===x?"selected":""} onClick={()=>setDevice(x)} type="button">{x}</button>)}</div><div className={"nx-preview "+device}><div className="nx-browser"><span>● ● ●</span><small>preview / {p.projectId}</small><b>{p.stage==="building"||p.stage==="editing"?"BUILDING":"LIVE"}</b></div><iframe ref={frame} title={p.projectName+" preview"} src={"/api/preview/"+p.projectId+"/index.html?v="+p.previewKey} sandbox="allow-scripts"/></div></>:<div className="nx-preview-empty"><div><span>PREVIEW</span><h2>Your app will appear here</h2><p>Send a request in the chat to start building the project.</p></div></div>}</section>;
 if(p.tab==="files")return <section className="nx-tool"><div className="nx-tool-head"><div><span>FILES</span><strong>Project source</strong></div><button type="button" onClick={()=>{setFiles([]);setSelected("")}}>Refresh</button></div><div className="nx-files"><aside>{loading&&!files.length?<p>Loading…</p>:files.map(f=><button className={selected===f?"selected":""} key={f} type="button" onClick={()=>setSelected(f)}>{f}</button>)}</aside><main>{selected?<><div className="nx-file-head"><b>{selected}</b><button disabled={!dirty||loading} onClick={()=>void save()}>{loading?"Saving…":dirty?"Save":"Saved"}</button></div><textarea spellCheck={false} value={content} onChange={e=>setContent(e.target.value)}/></>:<div className="nx-empty">Select a file</div>}</main></div>{error&&<div className="nx-error">{error}</div>}</section>;
 const live=Boolean(p.jobId)&&p.stage!=="completed"&&p.stage!=="error",current=p.stage==="thinking"||p.stage==="reading"?"analyzing":p.stage==="running"?"planning":p.stage==="building"?"editing":p.stage??"",idx=stages.findIndex(x=>x[0]===current);
 return <section className="nx-tool nx-agent"><div className="nx-tool-head"><div><span>AGENT</span><strong>{live?"Building your project":p.stage==="completed"?"Build completed":"Agent ready"}</strong></div><span className={"nx-agent-state "+(live?"live":"")}>{live?"Running":p.stage==="error"?"Error":"Ready"}</span></div><div className="nx-run"><strong>{p.currentActivity||"Ready for the next task"}</strong><span>{p.activitySteps.length} actions · {p.activitySteps.filter(x=>x.success).length} successful</span><div className="nx-progress">{stages.map((x,i)=><i className={i<idx||p.stage==="completed"?"done":i===idx&&live?"active":""} key={x[0]}/>)}</div></div><div className="nx-agent-list">{stages.map((x,i)=><div key={x[0]} className={i<idx||p.stage==="completed"?"done":i===idx&&live?"active":""}><b>{String(i+1).padStart(2,"0")}</b><span>{x[1]}</span></div>)}</div>{p.problems.length>0&&<div className="nx-problems"><strong>Problems</strong>{p.problems.slice(0,5).map((x,i)=><p key={i}>! {x.source?x.source+": ":""}{x.message}</p>)}<button type="button" onClick={p.onRepair}>Fix with Agent</button></div>}{p.productPlan&&<div className="nx-plan"><small>PRODUCT PLAN</small><strong>{p.productPlan.productType}</strong><p>{p.productPlan.goal}</p><span>{p.productPlan.pages.length} pages · {p.productPlan.components.length} components</span></div>}<div className="nx-events"><strong>Activity</strong>{p.activityEvents.length?[...p.activityEvents].reverse().slice(0,20).map(e=><p key={e.id}><b>{e.tool??"Agent"}</b> · {e.message}</p>):<span>No activity yet.</span>}</div></section>;
}