import { useEffect, useState } from "react";
interface RightPanelProps { tab: "preview" | "files" | "terminal"; onTabChange: (tab: "preview" | "files" | "terminal") => void; onOpenTerminal: () => void; projectName: string; projectId: string; previewOnline: boolean; previewKey: number; onRefreshPreview: () => void; }
export function RightPanel({ tab, onTabChange, onOpenTerminal, projectName, projectId, previewOnline, previewKey, onRefreshPreview }: RightPanelProps) {
  const previewUrl = projectId ? `/api/preview/${projectId}/index.html` : "";
  const [files, setFiles] = useState<string[]>([]); const [filesLoading, setFilesLoading] = useState(false); const [fileError, setFileError] = useState("");
  useEffect(() => { if (tab !== "files" || !projectId) return; let cancelled = false; setFilesLoading(true); setFileError("");
    fetch(`/api/projects/${encodeURIComponent(projectId)}/files`).then(async (response) => { const data = await response.json().catch(() => ({})) as { files?: string[]; error?: string }; if (!response.ok) throw new Error(data.error || `Files API: HTTP ${response.status}`); if (!cancelled) setFiles(data.files ?? []); }).catch((error) => { if (!cancelled) setFileError(error instanceof Error ? error.message : "Unable to load files"); }).finally(() => { if (!cancelled) setFilesLoading(false); });
    return () => { cancelled = true; };
  }, [tab, projectId, previewKey]);
  return <aside className="right-panel" aria-label="Project tools">
    <div className="panel-tabs" role="tablist"><button className={tab === "preview" ? "active" : ""} type="button" onClick={() => onTabChange("preview")}>Preview</button><button className={tab === "files" ? "active" : ""} type="button" onClick={() => onTabChange("files")}>Files</button><button className={tab === "terminal" ? "active" : ""} type="button" onClick={() => onTabChange("terminal")}>Terminal</button>{tab === "preview" && previewOnline && <button className="preview-refresh" type="button" onClick={onRefreshPreview} aria-label="Refresh preview">↻</button>}</div>
    {tab === "preview" ? (previewOnline ? <div className="preview-frame-wrap"><iframe key={previewKey} className="preview-frame" title={`${projectName} live preview`} src={previewUrl} sandbox="allow-scripts allow-forms allow-modals" /></div> : <div className="preview-content"><div className="preview-icon">{projectName.slice(0,1) || "N"}</div><strong>{projectName}</strong><div className="coming-soon">Preview is waiting for an index.html</div><span>Ask the Agent: “Создай приложение и запусти preview”</span></div>) : tab === "files" ? <div className="files-panel"><div className="files-panel-head"><span>PROJECT FILES</span><span>{files.length}</span></div>{filesLoading ? <div className="files-empty">Loading files...</div> : fileError ? <div className="files-empty error-state-inline">{fileError}</div> : <div className="file-tree">{files.map((file) => <button key={file} className="file-row" type="button"><span>{file.endsWith(".css") ? "◇" : file.endsWith(".js") || file.endsWith(".ts") || file.endsWith(".tsx") ? "ƒ" : file.endsWith(".json") ? "{}" : "□"}</span><strong>{file}</strong></button>)}</div>}</div> : <div className="terminal-empty"><span className="terminal-prompt">$</span><span>Use the Agent to run safe build and test commands.</span><button type="button" onClick={onOpenTerminal}>Open panel</button></div>}
  </aside>;
}