import * as vscode from "vscode";
import { OllamaClient } from "./ollamaClient.js";
function config(){const c=vscode.workspace.getConfiguration("nexum");return{url:c.get<string>("ollamaUrl","http://127.0.0.1:11434").replace(/\\/+$/,""),model:c.get<string>("defaultModel","qwen3:4b")}}
function client(){return new OllamaClient(config().url)}
async function context(){const e=vscode.window.activeTextEditor;if(!e)return"No active file.";const selected=!e.selection.isEmpty?e.document.getText(e.selection):e.document.getText();return"FILE: "+vscode.workspace.asRelativePath(e.document.uri)+"\nLANGUAGE: "+e.document.languageId+"\nCONTENT:\n"+selected.slice(0,30000)}
async function check(){const s=await client().status();if(!s.available){void vscode.window.showErrorMessage("Nexum Local AI: "+(s.error??"Ollama unavailable"));return}const m=await client().listModels();void vscode.window.showInformationMessage("Nexum Local AI online — Ollama "+(s.version??"unknown")+", "+m.length+" model(s).")}
async function install(){const input=await vscode.window.showInputBox({title:"Install local AI model",prompt:"Ollama model name",value:config().model,placeHolder:"qwen3:4b"});if(!input)return;await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:"Nexum: installing "+input},async()=>{try{await client().pull(input.trim());void vscode.window.showInformationMessage("Nexum: "+input+" installed locally.")}catch(e){void vscode.window.showErrorMessage(e instanceof Error?e.message:"Model installation failed.")}})}
async function ask(){const prompt=await vscode.window.showInputBox({title:"Ask Nexum Local AI",prompt:"Development task",placeHolder:"Analyze this file and propose a fix..."});if(!prompt)return;const model=config().model;await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:"Nexum: asking "+model},async()=>{try{const answer=await client().chat(model,prompt,await context());const d=await vscode.workspace.openTextDocument({language:"markdown",content:"# Nexum Local AI\n\nModel: "+model+"\n\n"+answer+"\n"});await vscode.window.showTextDocument(d,vscode.ViewColumn.Beside)}catch(e){void vscode.window.showErrorMessage(e instanceof Error?e.message:"Local AI request failed.")}})}
export function activate(ctx:vscode.ExtensionContext){ctx.subscriptions.push(vscode.commands.registerCommand("nexum.checkLocalAI",check),vscode.commands.registerCommand("nexum.installModel",install),vscode.commands.registerCommand("nexum.askLocalAI",ask),vscode.commands.registerCommand("nexum.openAgent",ask))}
export function deactivate(){}
