
import {RuntimeEventBus} from "./EventBus";import {RuntimeDiagnostics} from "./Diagnostics";import {ResourceManager} from "./ResourceManager";import {TaskManager}from"./TaskManager";import{RuntimeScheduler}from"./Scheduler";import{NetworkManager}from"./NetworkManager";import{RuntimePersistence}from"./Persistence";import{RecoveryCore}from"./RecoveryCore";import{ProcessSupervisor}from"./ProcessSupervisor";import{PerformanceMonitor}from"./PerformanceMonitor";import{PreviewManager}from"./PreviewManager";import{VisualRuntime}from"./VisualRuntime";import type{RuntimeContext,RuntimeLifecycle,RuntimeSnapshot}from"./types";\nimport { failureInjection } from "./FailureInjection.ts";
export class NexumRuntime{
 readonly events=new RuntimeEventBus();readonly diagnostics=new RuntimeDiagnostics();readonly resources=new ResourceManager(this.events,this.diagnostics);readonly tasks=new TaskManager(this.events,this.diagnostics);readonly scheduler=new RuntimeScheduler(this.tasks,4);readonly network=new NetworkManager(this.diagnostics);readonly persistence=new RuntimePersistence();readonly recovery=new RecoveryCore(this.diagnostics);readonly processes=new ProcessSupervisor(this.events,this.diagnostics);readonly performance=new PerformanceMonitor(this.events,this.diagnostics);readonly preview=new PreviewManager(this.events,this.diagnostics);readonly visual=new VisualRuntime(this.events,this.diagnostics);
 private lifecycle:RuntimeLifecycle="BOOTING";private started=false;private projectId?:string;private health={APP:"HEALTHY",AI:"HEALTHY",AGENT:"HEALTHY",NETWORK:"HEALTHY",PREVIEW:"HEALTHY",PROCESS:"HEALTHY",WORKERS:"HEALTHY",STATE:"HEALTHY",STORAGE:"HEALTHY",VISUAL:"HEALTHY"} as Record<string,"HEALTHY"|"DEGRADED"|"RECOVERING"|"FAILED">;
 async start(context:RuntimeContext={}){if(this.started)return;this.lifecycle="BOOTING";this.events.open();const snapshot=this.persistence.load();this.projectId=context.projectId??snapshot?.activeProjectId;this.events.emit("runtime:booting");this.performance.start();this.started=true;this.lifecycle="READY";this.events.emit("runtime:ready",{snapshot},context);this.recomputeHealth();this.diagnostics.info("RUNTIME","Runtime ready",{projectId:this.projectId})}
 setProject(projectId?:string){this.projectId=projectId;this.events.emit("runtime:project-changed",{projectId});this.save()}
 setBusy(v=true){if(this.lifecycle==="SHUTTING_DOWN")return;this.lifecycle=v?"BUSY":"READY";this.events.emit("runtime:lifecycle",{lifecycle:this.lifecycle})}
 degrade(reason:string){this.lifecycle="DEGRADED";this.diagnostics.warn("RUNTIME",reason,{projectId:this.projectId});this.events.emit("runtime:degraded",{reason})}
 getHealth(){return {...this.health}}
 private recomputeHealth(){const preview=this.preview.state==="FAILED"?"FAILED":this.preview.state==="UNHEALTHY"||this.preview.state==="RESTARTING"?"DEGRADED":"HEALTHY";const visual=this.performance.getHealth()==="CRITICAL"?"DEGRADED":this.performance.getHealth()==="NORMAL"?"HEALTHY":"DEGRADED";this.health.PREVIEW=preview;this.health.VISUAL=visual;this.health.NETWORK=this.network.isOnline()?"HEALTHY":"DEGRADED";this.health.PROCESS=this.processes.getActiveCount()===0?"HEALTHY":"HEALTHY";const degraded=Object.values(this.health).some(v=>v==="DEGRADED"||v==="RECOVERING");const failed=Object.values(this.health).some(v=>v==="FAILED");if(failed)this.lifecycle="DEGRADED";else if(degraded&&this.lifecycle==="READY")this.lifecycle="DEGRADED";return failed?"DEGRADED":degraded?"DEGRADED":"READY"}
 recover(){this.lifecycle="RECOVERING";this.events.emit("runtime:recovering");this.recomputeHealth();this.lifecycle=this.getHealthState();this.events.emit("runtime:ready")}
 private getHealthState():RuntimeLifecycle{return Object.values(this.health).some(v=>v==="FAILED"||v==="DEGRADED")?"DEGRADED":"READY"}
 getLifecycle(){return this.lifecycle}
 save(){const s:RuntimeSnapshot={version:1,savedAt:Date.now(),lifecycle:this.lifecycle,activeProjectId:this.projectId,activeTaskIds:this.tasks.list().filter(t=>!["COMPLETED","FAILED","CANCELLED"].includes(t.status)).map(t=>t.id),metadata:{health:this.performance.getHealth(),fps:this.performance.getFps()}};this.persistence.save(s)}
 async shutdown(){if(!this.started)return;this.lifecycle="SHUTTING_DOWN";this.events.emit("runtime:shutting-down");this.tasks.list().filter(t=>!["COMPLETED","FAILED","CANCELLED"].includes(t.status)).forEach(t=>{this.network.cancelTask(t.id);this.tasks.cancel(t.id)});await this.preview.stop();this.processes.stopAll();this.resources.releaseAll();this.visual.releaseAll();this.performance.stop();this.save();this.network.destroy();this.started=false;this.events.close()}
}
export const nexumRuntime=new NexumRuntime();
