
import {RuntimeEventBus} from "./EventBus.ts";import {RuntimeDiagnostics} from "./Diagnostics.ts";import {ResourceManager} from "./ResourceManager.ts";import {TaskManager}from "./TaskManager.ts";import{RuntimeScheduler}from "./Scheduler.ts";import{NetworkManager}from "./NetworkManager.ts";import{RuntimePersistence}from "./Persistence.ts";import{RecoveryCore}from "./RecoveryCore.ts";import{ProcessSupervisor}from "./ProcessSupervisor.ts";import{PerformanceMonitor}from "./PerformanceMonitor.ts";import{PreviewManager}from "./PreviewManager.ts";import{VisualRuntime}from "./VisualRuntime.ts";import type{RuntimeContext,RuntimeLifecycle,RuntimeSnapshot}from "./types.ts";
import { failureInjection } from "./FailureInjection.ts";
const VALID_RUNTIME_TRANSITIONS: Record<RuntimeLifecycle, RuntimeLifecycle[]> = {
 BOOTING:["READY","DEGRADED","SHUTTING_DOWN"],READY:["BUSY","DEGRADED","RECOVERING","SHUTTING_DOWN"],BUSY:["READY","DEGRADED","RECOVERING","SHUTTING_DOWN"],DEGRADED:["READY","RECOVERING","SHUTTING_DOWN"],RECOVERING:["READY","DEGRADED","SHUTTING_DOWN"],SHUTTING_DOWN:["BOOTING"]
};

export class NexumRuntime{
 readonly events=new RuntimeEventBus();
 constructor(){this.events.on("*",event=>{if(event.type.startsWith("preview:")||event.type.startsWith("process:")||event.type.startsWith("performance:"))this.recomputeHealth();});}
 readonly diagnostics=new RuntimeDiagnostics();readonly resources=new ResourceManager(this.events,this.diagnostics);readonly tasks=new TaskManager(this.events,this.diagnostics);readonly scheduler=new RuntimeScheduler(this.tasks,4);readonly network=new NetworkManager(this.diagnostics);readonly persistence=new RuntimePersistence();readonly recovery=new RecoveryCore(this.diagnostics);readonly processes=new ProcessSupervisor(this.events,this.diagnostics);readonly performance=new PerformanceMonitor(this.events,this.diagnostics);readonly preview=new PreviewManager(this.events,this.diagnostics);readonly visual=new VisualRuntime(this.events,this.diagnostics);
 private lifecycle:RuntimeLifecycle="BOOTING";private started=false;
 private transition(next:RuntimeLifecycle){if(next===this.lifecycle)return true;if(!VALID_RUNTIME_TRANSITIONS[this.lifecycle].includes(next)){this.diagnostics.warn("RUNTIME",`Invalid lifecycle transition ${this.lifecycle} -> ${next}`,{projectId:this.projectId});return false;}this.lifecycle=next;this.events.emit("runtime:lifecycle",{lifecycle:next});return true;}private projectId?:string;private health={APP:"HEALTHY",AI:"HEALTHY",AGENT:"HEALTHY",NETWORK:"HEALTHY",PREVIEW:"HEALTHY",PROCESS:"HEALTHY",WORKERS:"HEALTHY",STATE:"HEALTHY",STORAGE:"HEALTHY",VISUAL:"HEALTHY"} as Record<string,"HEALTHY"|"DEGRADED"|"RECOVERING"|"FAILED">;
 async start(context:RuntimeContext={}){if(this.started)return;this.transition("BOOTING");this.events.open();const snapshot=this.persistence.load();if(!snapshot&&typeof localStorage!=="undefined"&&localStorage.getItem("nexum:runtime:snapshot:v1")){this.health.STATE="DEGRADED";this.diagnostics.warn("STATE","Persisted runtime snapshot failed validation; safe fallback used",{projectId:context.projectId});}if(failureInjection.isEnabled("FAIL_STATE_RESTORE")){this.health.STATE="DEGRADED";this.diagnostics.warn("STATE","Injected snapshot restore failure; safe fallback used",{projectId:context.projectId});}this.projectId=context.projectId??snapshot?.activeProjectId;this.events.emit("runtime:booting");this.performance.start();this.started=true;this.transition("READY");this.events.emit("runtime:ready",{snapshot},context);this.recomputeHealth();this.diagnostics.info("RUNTIME","Runtime ready",{projectId:this.projectId})}
 setProject(projectId?:string){this.projectId=projectId;this.events.emit("runtime:project-changed",{projectId});this.save()}
 setBusy(v=true){if(this.lifecycle==="SHUTTING_DOWN")return;this.transition(v?"BUSY":"READY")}
 degrade(reason:string){this.transition("DEGRADED");this.diagnostics.warn("RUNTIME",reason,{projectId:this.projectId});this.events.emit("runtime:degraded",{reason})}
 getHealth(){return {...this.health}}
 getInspection(){return {lifecycle:this.lifecycle,projectId:this.projectId,health:{...this.health},tasks:this.tasks.list(),activeTasks:this.tasks.list().filter(t=>!["COMPLETED","FAILED","CANCELLED"].includes(t.status)).length,resources:this.resources.snapshot(),activeResources:this.resources.snapshot().filter(r=>r.status!=="RELEASED").length,network:this.network.getActive(),preview:{state:this.preview.state,restartCount:this.preview.getRestartCount()},processes:this.processes.list(),visual:this.visual.getState(),performance:{health:this.performance.getHealth(),fps:this.performance.getFps()},diagnostics:this.diagnostics.list().slice(-100),failures:failureInjection.list(),failureDiagnostics:failureInjection.diagnostics()};}
 private recomputeHealth(){const preview=this.preview.state==="FAILED"?"FAILED":this.preview.state==="UNHEALTHY"||this.preview.state==="RESTARTING"?"DEGRADED":"HEALTHY";const visual=this.performance.getHealth()==="CRITICAL"?"DEGRADED":this.performance.getHealth()==="NORMAL"?"HEALTHY":"DEGRADED";this.health.PREVIEW=preview;this.health.VISUAL=visual;this.health.NETWORK=this.network.isOnline()?"HEALTHY":"DEGRADED";this.health.PROCESS=this.processes.getActiveCount()===0?"HEALTHY":"HEALTHY";const degraded=Object.values(this.health).some(v=>v==="DEGRADED"||v==="RECOVERING");const failed=Object.values(this.health).some(v=>v==="FAILED");if(failed)this.transition("DEGRADED");else if(degraded&&this.lifecycle==="READY")this.transition("DEGRADED");else if(!degraded&&this.lifecycle==="DEGRADED")this.transition("READY");return failed?"DEGRADED":degraded?"DEGRADED":"READY"}
 recover(){this.transition("RECOVERING");this.events.emit("runtime:recovering");this.recomputeHealth();this.transition(this.getHealthState());this.events.emit("runtime:ready")}
 private getHealthState():RuntimeLifecycle{return Object.values(this.health).some(v=>v==="FAILED"||v==="DEGRADED")?"DEGRADED":"READY"}
 getLifecycle(){return this.lifecycle}
 save(){const s:RuntimeSnapshot={version:1,savedAt:Date.now(),lifecycle:this.lifecycle,activeProjectId:this.projectId,activeTaskIds:this.tasks.list().filter(t=>!["COMPLETED","FAILED","CANCELLED"].includes(t.status)).map(t=>t.id),metadata:{health:this.performance.getHealth(),fps:this.performance.getFps()}};this.persistence.save(s)}
 async shutdown(){if(!this.started)return;this.transition("SHUTTING_DOWN");this.events.emit("runtime:shutting-down");this.tasks.list().filter(t=>!["COMPLETED","FAILED","CANCELLED"].includes(t.status)).forEach(t=>{this.network.cancelTask(t.id);this.tasks.cancel(t.id)});await this.preview.stop();this.processes.stopAll();this.resources.releaseAll();this.visual.releaseAll();this.performance.stop();this.save();this.network.destroy();this.started=false;this.events.close()}
}
export const nexumRuntime=new NexumRuntime();
